# Generated by Django 5.0.4 on 2024-10-13 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(help_text='Enter family name', max_length=50)),
                ('address', models.CharField(help_text='Enter residence address', max_length=50)),
            ],
            options={
                'ordering': ['family_name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=50)),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=50)),
                ('date_of_birth', models.DateField(help_text='Enter date of birth')),
                ('type_of_member', models.CharField(choices=[('PR', 'Parent'), ('SN', 'Son'), ('DT', 'Daughter'), ('OT', 'Other')], default='OT', max_length=2)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='familyapp.family')),
            ],
        ),
    ]
